[env]
TERM = "xterm-256color"

[window]
decorations = "None"
dynamic_padding = true
opacity = 0.9
blur = true

[window.padding]
x = 25
y = 20

[font]
size = 13.0

[font.bold]
family = "JetBrainsMono Nerd Font"
# family = "Geist Mono"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
# family = "Geist Mono"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
# family = "Geist Mono"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
# family = "Geist Mono"
style = "Medium"

[general]
live_config_reload = true
import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/usr/bin/fish"
# args = ["-c",  "/usr/bin/tmux"]
