[colors.primary]
background = '#171217'
foreground = '#eadfe6'
 
[colors.cursor]
text = '#eadfe6'
cursor = '#d0c3cc' 
 
[colors.vi_mode_cursor]
text = '#171217'
cursor = '#ebb5ed' 
 
[colors.search.matches]
foreground = '#4d444c' 
background = '#f6b8ae' 
 
[colors.search.focused_match]
foreground = '#4d444c' 
background = '#ebb5ed' 
 
[colors.footer_bar]
foreground = '#4d444c' 
background = '#eadfe6' 
 
[colors.hints.start]
foreground = '#4d444c' 
background = '#d7bfd5' 
 
[colors.hints.end]
foreground = '#4d444c' 
background = '#d7bfd5' 
 
[colors.selection]
text = '#171217'
background = '#ebb5ed'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#ebb5ed' 
yellow = '#7b4e7f' 
blue = '#ebb5ed' 
magenta = '#f6b8ae' 
cyan = '#d7bfd5' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
