theme = "catppuccin_mocha"

[editor]
line-number = "relative"

# show up the buffer up top
bufferline = "always"


# always use the system clipboard
default-yank-register = '_'
popup-border = "all"
cursorline = true
color-modes = true
true-color = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true


[editor.lsp]
display-messages = true
display-inlay-hints = true


[editor.whitespace.characters]
#space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
#tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.normal."'"]
y = ":sh zellij run --floating -n 'yazi picker' -- /home/Abdullah/.config/fish/scripts/open_in_helix_from_yazi.fish"

[keys.normal]

# My configuration

#----------
# moves a line up and down
A-K = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-J = ["extend_to_line_bounds", "delete_selection", "paste_after"]

# exists the multiline select
#esc = ["keep_primary_selection", "collapse_selection"]

# closes the current buffer
space = { x = ":buffer-close" }


# to switch between opened buffers
tab = ":buffer-next"
S-tab = ":buffer-previous"

esc = ["collapse_selection", "keep_primary_selection"]
"_" = "goto_first_nonwhitespace"


[keys.insert]

esc = ["collapse_selection", "normal_mode"]


[keys.select]

# My configuration
# ------

# moves a line up and down, but for multiple selected lines
A-K = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-J = ["extend_to_line_bounds", "delete_selection", "paste_after"]

C-o = "flip_selections"
"_" = "goto_first_nonwhitespace"
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

# ------
